name: build

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        debian: [9.13, 10.13, 11.6, bookworm, sid]
        busybox: [1.33.2, 1.34.1, 1.35.0]    
        #exclude:
        #  - debian: 9.13
        #    busybox: 1.36.0
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          build-args: |
            DEBIAN=${{ matrix.debian }}
            BUSYBOX=${{ matrix.busybox }}
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: |
            ghcr.io/bfren/busybox:${{ matrix.busybox }}-debian${{ matrix.debian }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
