name: build-alpine

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        alpine: ["3.15.11", "3.16.9", "3.17.10", "3.18.12", "3.19.7", "3.20.6", "3.21.3"]
        busybox: ["1.34.1", "1.36.1", "1.37.0"]
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.alpine
          build-args: |
            ALPINE=${{ matrix.alpine }}
            ALPINE_BRANCH=3.20
            BUSYBOX=${{ matrix.busybox }}
          push: true
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: |
            ghcr.io/bfren/busybox:${{ matrix.busybox }}-alpine${{ matrix.alpine }}-${{ steps.version.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
