name: build

on:
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        busybox: [1.33.2, 1.34.1, 1.35.0]
        debian: [10.13, 11.5, bookworm, sid]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            BUSYBOX=${{ matrix.busybox }}
            DEBIAN=${{ matrix.debian }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            ghcr.io/bfren/busybox:${{ matrix.busybox }}-debian${{ matrix.debian }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
